(defun html () 
  (page "{adjective} websites" `((section () 
                                          (h1 () "{adjective} websites")
                                          (ul ()
                                            (li () 
                                              (a (:href "https://eightyeightthirty.one/") "eightyeightthirty.one") 
                                              " a graph of website badges.")
                                            (li () 
                                              (a (:href "http://lena.kiev.ua/") "lena.kiev.ua") 
                                            (li () 
                                              (a (:href "https://www.webcoves.com/tgring.html") "transgendering") 
                                              " this one is interesting to explore.")
                                            (li () 
                                              (a (:href "https://ftp.cdc.gov/pub/GOODMAN/") "ftp.cdc.gov/pub/GOODMAN/") 
                                              " cdc saul goodman.")
                                            (li () 
                                              (a (:href "https://wiki.alquds.edu/?query=Main_Page") "wiki.alquds.edu/?query=Main_Page") 
                                              " weird wikipedia mirror.")
                                            (li () 
                                              (a (:href "https://lhohq.info/") "lhohq.info") 
                                              " who knows.")
                                            (li () 
                                              (a (:href "http://plaza.ufl.edu/virus86") "plaza.ufl.edu/virus86") 
                                              " a random ufl student's files sitting on some university server somewhere, for some reason.")
                                            (li () 
                                              (a (:href "https://www.cs.arizona.edu/icon") "www.cs.arizona.edu/icon") 
                                              " a cool programming language.")
                                            (li () 
                                              (a (:href "https://observatory.db.erau.edu/generators/signs/") "observatory.db.erau.edu/generators/signs/") 
                                              " warning sign generator.")
                                            (li () 
                                              (a (:href "https://adams.nrc.gov/wba/") "adams.nrc.gov/wba") 
                                              " nuclear regulatory commission agencywide documents access and management system.")
                                            (li () 
                                              (a (:href "https://owd.tcnj.edu/~hofmann/") "owd.tcnj.edu/~hofmann") 
                                              " random professor's homepage.")
                                            (li () 
                                              (a (:href "https://citrons.xyz") "citrons.xyz") 
                                              " this entity seems odd.")
                                            (li () 
                                              (a (:href "https://w3.pppl.gov") "w3.pppl.gov") 
                                              " i quite like the w3 subdomain of the princeton plasma physics laboratory.")
                                            (li () 
                                              (a (:href "https://eda.gay") "eday.gay") 
                                              " she owns less thinkpads than this one does. brainwormed.")
                                            (li () 
                                              (a (:href "https://www.yourworldoftext.com/apionet") "https://www.yourworldoftext.com/apionet") 
                                              " buzzzzzzzzzzzzzzzzzzz")))
                                          "this website compelled natalie to put it somewhere:" 
                                          (a (:href "https://citrons.xyz/a/memetic-apioform-page.html") (img (:src "https://citrons.xyz/a/static/apiopage.png"))))
                                 (section () 
                                          (h2 () "entities that it sometimes interact with physically")
                                          (span () 
                                            "winter: " 
                                            (a (:href "https://bunbun.dev") "bunbun.dev")
                                            (a (:href "https://bunbun.dev")
                                              (img (:style "float: right" :src "../files/88x31/bunbun.dev.gif"))))
                                          (span ()
                                            "odette: " 
                                            (a (:href "http://puppygirl.systems") "puppygirl.systems (stupid idiot who types &lt;hr/&gt;)")
                                            " Semi functional now")
                                          (span ()
                                            "unnamed friend entity: " 
                                            (a (:href "https://iso-9995-9.com") "iso-9995-9.com")
                                            " (down? dns issue maybe)")
                                          (span ()
                                            "sam: " 
                                            (a (:href "https://hellzone.org") "hellzone.org")
                                            (a (:href "https://hellzone.org")
                                              (img (:style "float: right" :src "https://hellzone.org/src/images/88x31.gif"))))))))


