(defun html () 
  (page "natalie info" `((section () 
                                  (h1 () "what is a \"natalie\"?")
                                  (span () 
                                        "it is <a href='/html/natalie-sightings.html'>natalie</a>."
                                        ,(exec-command "make-footnote 'the natalie is provided \"as is\", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, title and non-infringement. in no event shall the copyright holders or anyone distributing the natalie be liable for any damages or other liability, whether in contract, tort or otherwise, arising from, out of or in connection with the natalie or the use or other dealings in the natalie.'")
                                        "obviously.")
                                  (p () 
                                     "words are not a thing it is good at. this is exacerbaited when the words are about itself. "
                                     "despite this, it shall attempt a suitable description of itself.")
                                  (br)
                                  (p ()
                                  "ideally, natalie is to be referred to as an \"it\" or a \"she\".",(exec-command "make-footnote \" the former is preferred.\"") "additionally, it generally prefers being referred to using 3rd person pronouns, or as \"this thing\" or \"that one\". it supposes it may reasonably be described as asexual. " (br)
                                  "timezone it is in: PST/PDT" (br)
                                  "age: $[echo $(( $(date +%s) - $(date -d \"2007-04-01\" +%s) ))] seconds. that is $[echo \"scale=8; ($(date +%s) - $(date -d '2007-04-01' +%s)) / (365.25*24*3600)\" | bc] [earth] years." (br)
                                  "it is kind of a college student. this is complicated. it will be a college student with less complicated circumstances by fall of 2025, barring unforseen circumstances." (br)
                                  "natalie likes systems. particularly ones that have reasonably consistent behavior based on a set of rules. this is omnipresent in its interests." (br)
                                  "list of its interests (incomplete):" 
                                  (ul () 
                                      (li () "technical computer things, so long as they do not involve javascript")
                                      (li () "infrastructure, particularly pertaining to trains")
                                      (li () "languistics, especially conlangs")
                                      (li () "key making and lock picking")
                                      (li () "math"))
                                  "things that it enjoys:" 
                                  (ul () 
                                      (li () "friends")
                                      (li () "going on long walks")
                                      (li () "utilizing public transportation")
                                      (li () "train tracks"))
                                  "things that it finds displeasing:"
                                  (ul () 
                                      (li () "grease or oil on its skin")
                                      (li () "non friend people") 
                                      (li () "ultraviolet radiation")
                                      (li () "busywork")))
                                  ,(exec-command "put-footnotes"))
                         (section ()
                                  (h2 () "somewhat irregular natalie facts")
                                  (ul () 
                                      (li () "it owns 12 thinkpads, all of which were manufactured prior to 2014")
                                      (li () "the number of people that can effectively use its computer is, to its knowledge, 1 (natalie)" ,(exec-command "make-footnote \"the number of people it knows who can type on it is 3, including itself\""))
                                      (li () "it can replace the screen on its first generation iphone se a1662 in 70 seconds"))
                                  ,(exec-command "put-footnotes"))
                         (section () 
                                  (h2 () "contact information")
                                  (a (:href "/html/discord.html") "discord: _natalieeee_")
                                  "email: natalie at natalieee.net" (br) 
                                  "xmpp: nat@natalieee.net")
                         (section () 
                                  (h2 () "some of its computers")
                                  (p () "it owns many computers, none of them are normal. particularly notable instances of this phenomenon will be noted below:")
                                  (ul () 
                                      (li () ,(exec-command "make-link /html/its-laptop.html 'its framework 16'")
                                      (li () ,(exec-command "make-link /html/its-old-laptop.html 'its old {w,t}530'"))
                                      (li () ,(exec-command "make-link /html/server-migration.html 'the server this site runs on'"))))))))
