(defun html () 
  (page "natalie \"thoughts\"" `((section () 
                   (h1 () "arbitrary thoughts generated by natalie")
                   "it is bad lat thinking of things to make blog posts for. this webpage might contain things that it would put in a blog post if it was more proficient at writing filler. it might also contain other things.")
          ,(exec-command "for file in ./html/thoughts/*; do echo $(grep DATE $file | awk '{print $3 $4}') $file; done | sort -k1,1 -r | cut -d' ' -f2 | while read -r file; do echo \"<section><details id='$(basename $file)'><summary>$(grep '^<!-- DATE:' $file | sed 's/^<!-- DATE: //; s/-->$//; s/.$//'): $(grep '^<!-- TITLE:' $file | sed 's/^<!-- TITLE: //; s/-->$//')</summary><div class=thought>$(include $file)</details></section>\"; done"))))

