(defun header () 
  '(header () 
           (nav () 
                (ul ()
                    (li () 
                        (h1 () "$[(for i in {0..10}; do echo natalieee.net; done; echo catalieee.net) | shuf -n1]"))
                    (li ()
                        (a (:href "/") "home"))
                    (li ()
                        (a (:href "..") "back"))
                    (li ()
                        (a (:href "/html/site-info.html") "site info"))
                    (li () 
                        (a (:href "/html/natalie-info.html") "natalie info"))))))
